# Generated by Django 4.0.3 on 2022-04-10 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('event', 'guest')},
        ),
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together={('event', 'guest')},
        ),
    ]
