# Generated by Django 4.0.3 on 2022-04-10 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_guest_is_blocked'),
        ('events', '0002_alter_application_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firsttypeevent',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='first_type_events', to='users.manager', verbose_name='Менеджер'),
        ),
        migrations.AlterField(
            model_name='secondtypeevent',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='second_type_events', to='users.manager', verbose_name='Менеджер'),
        ),
    ]
