# Generated by Django 4.0.3 on 2022-04-11 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0003_alter_firsttypeevent_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='guest',
            field=models.ForeignKey(limit_choices_to={'type': 'guest'}, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='Гость'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='guest',
            field=models.ForeignKey(limit_choices_to={'type': 'guest'}, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Гость'),
        ),
        migrations.AlterField(
            model_name='firsttypeevent',
            name='manager',
            field=models.ForeignKey(limit_choices_to={'type': 'manager'}, on_delete=django.db.models.deletion.PROTECT, related_name='first_type_events', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер'),
        ),
        migrations.AlterField(
            model_name='secondtypeevent',
            name='manager',
            field=models.ForeignKey(limit_choices_to={'type': 'manager'}, on_delete=django.db.models.deletion.PROTECT, related_name='second_type_events', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер'),
        ),
    ]
